sources:
  - https://www.world-newspapers.com/magazines/military
  - https://tass.com/defense
  - https://t.me/faceofwar
  - https://t.me/warriorofnorth
  - https://t.me/Cbpub
  - https://t.me/infantmilitario
  - https://t.me/warmempolit
  - https://t.me/UAVDEV
  - https://t.me/auantonov
  - https://t.me/Sladkov_plus
  - https://t.me/okspn
  - https://t.me/pograni4nik_iz_ada
  - https://www.military.com
  - https://www.militarytimes.com
  - https://www.defensenews.com
  - https://www.armytimes.com
  - https://www.foxnews.com/category/us/military